//------------------------------------------------------------------------------
// AssemblyInfo.cs
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------
using Microsoft.Dss.Core.Attributes;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;

using System.Reflection;
using Microsoft.Dss.Core;

[assembly: ServiceDeclaration(DssServiceDeclaration.ServiceBehavior)]
[assembly: interopservices.ComVisible(false)]
[assembly: AssemblyTitle("Maze Simulator Service")]
[assembly: AssemblyProduct("Maze Simulator Service")]
[assembly: AssemblyVersion("2.0")]
[assembly: AssemblyCopyright("Written by Trevor Taylor")]
[assembly: AssemblyDescription("Allows simple maze-like environments for be built for the Simulator. This version is freely available.")]
[assembly: AssemblyCompany("Software Technology")]

